# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simulator.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Simulator(object):
    def setupUi(self, Simulator):
        Simulator.setObjectName("Simulator")
        Simulator.resize(936, 576)
        Simulator.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(Simulator)
        self.centralwidget.setObjectName("centralwidget")
        self.alphaHorizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.alphaHorizontalSlider.setGeometry(QtCore.QRect(690, 110, 160, 21))
        self.alphaHorizontalSlider.setMaximum(10)
        self.alphaHorizontalSlider.setProperty("value", 1)
        self.alphaHorizontalSlider.setTracking(True)
        self.alphaHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.alphaHorizontalSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.alphaHorizontalSlider.setTickInterval(1)
        self.alphaHorizontalSlider.setObjectName("alphaHorizontalSlider")
        self.phiHorizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.phiHorizontalSlider.setEnabled(True)
        self.phiHorizontalSlider.setGeometry(QtCore.QRect(690, 200, 160, 21))
        self.phiHorizontalSlider.setMaximum(5)
        self.phiHorizontalSlider.setTracking(True)
        self.phiHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.phiHorizontalSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.phiHorizontalSlider.setTickInterval(1)
        self.phiHorizontalSlider.setObjectName("phiHorizontalSlider")
        self.betaHorizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.betaHorizontalSlider.setGeometry(QtCore.QRect(689, 290, 161, 21))
        self.betaHorizontalSlider.setMaximum(20)
        self.betaHorizontalSlider.setSingleStep(1)
        self.betaHorizontalSlider.setProperty("value", 1)
        self.betaHorizontalSlider.setTracking(True)
        self.betaHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.betaHorizontalSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.betaHorizontalSlider.setTickInterval(1)
        self.betaHorizontalSlider.setObjectName("betaHorizontalSlider")
        self.wHorizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.wHorizontalSlider.setGeometry(QtCore.QRect(690, 390, 161, 21))
        self.wHorizontalSlider.setMinimum(1)
        self.wHorizontalSlider.setMaximum(10)
        self.wHorizontalSlider.setSliderPosition(1)
        self.wHorizontalSlider.setTracking(True)
        self.wHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.wHorizontalSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.wHorizontalSlider.setTickInterval(1)
        self.wHorizontalSlider.setObjectName("wHorizontalSlider")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(710, 65, 121, 31))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(640, 155, 251, 31))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(670, 245, 201, 31))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_4.setGeometry(QtCore.QRect(670, 345, 201, 31))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.diffLabel = QtWidgets.QLabel(self.centralwidget)
        self.diffLabel.setGeometry(QtCore.QRect(70, 450, 261, 61))
        self.diffLabel.setText("")
        self.diffLabel.setObjectName("diffLabel")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(670, 100, 16, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(670, 200, 16, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(670, 280, 16, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(670, 390, 16, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(860, 100, 16, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(860, 200, 31, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(860, 280, 16, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(860, 390, 16, 16))
        self.label_8.setObjectName("label_8")
        self.graphWidget = QtWidgets.QWidget(self.centralwidget)
        self.graphWidget.setGeometry(QtCore.QRect(10, 0, 621, 421))
        self.graphWidget.setObjectName("graphWidget")
        Simulator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Simulator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 936, 21))
        self.menubar.setObjectName("menubar")
        Simulator.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Simulator)
        self.statusbar.setObjectName("statusbar")
        Simulator.setStatusBar(self.statusbar)

        self.retranslateUi(Simulator)
        QtCore.QMetaObject.connectSlotsByName(Simulator)

    def retranslateUi(self, Simulator):
        _translate = QtCore.QCoreApplication.translate
        Simulator.setWindowTitle(_translate("Simulator", "Simulator"))
        self.textBrowser.setHtml(_translate("Simulator", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">A - амплитуда</p></body></html>"))
        self.textBrowser_2.setHtml(_translate("Simulator", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">φ0 - начальный градус отклонения</p></body></html>"))
        self.textBrowser_3.setHtml(_translate("Simulator", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">B - коэффициент затухания</p></body></html>"))
        self.textBrowser_4.setHtml(_translate("Simulator", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ω - частота колебаний</p></body></html>"))
        self.label.setText(_translate("Simulator", "0"))
        self.label_2.setText(_translate("Simulator", "0"))
        self.label_3.setText(_translate("Simulator", "0"))
        self.label_4.setText(_translate("Simulator", "1"))
        self.label_5.setText(_translate("Simulator", "10"))
        self.label_6.setText(_translate("Simulator", "Pi/2"))
        self.label_7.setText(_translate("Simulator", "2"))
        self.label_8.setText(_translate("Simulator", "10"))
