# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simulator.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Simulator(object):
    def setupUi(self, Simulator):
        Simulator.setObjectName("Simulator")
        Simulator.resize(854, 523)
        self.centralwidget = QtWidgets.QWidget(Simulator)
        self.centralwidget.setObjectName("centralwidget")
        self.alphaHorizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.alphaHorizontalSlider.setGeometry(QtCore.QRect(570, 80, 160, 16))
        self.alphaHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.alphaHorizontalSlider.setObjectName("alphaHorizontalSlider")
        self.phiHorizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.phiHorizontalSlider.setEnabled(True)
        self.phiHorizontalSlider.setGeometry(QtCore.QRect(570, 160, 160, 16))
        self.phiHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.phiHorizontalSlider.setObjectName("phiHorizontalSlider")
        self.betaHorizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.betaHorizontalSlider.setGeometry(QtCore.QRect(570, 240, 160, 16))
        self.betaHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.betaHorizontalSlider.setObjectName("betaHorizontalSlider")
        self.wHorizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.wHorizontalSlider.setGeometry(QtCore.QRect(570, 320, 160, 16))
        self.wHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.wHorizontalSlider.setObjectName("wHorizontalSlider")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(590, 40, 121, 31))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(530, 120, 251, 31))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(550, 200, 201, 31))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_4.setGeometry(QtCore.QRect(550, 270, 201, 31))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.diffTextBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.diffTextBrowser.setGeometry(QtCore.QRect(80, 360, 401, 71))
        self.diffTextBrowser.setObjectName("diffTextBrowser")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(60, 50, 451, 281))
        self.graphicsView.setObjectName("graphicsView")
        Simulator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Simulator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 854, 21))
        self.menubar.setObjectName("menubar")
        Simulator.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Simulator)
        self.statusbar.setObjectName("statusbar")
        Simulator.setStatusBar(self.statusbar)

        self.retranslateUi(Simulator)
        QtCore.QMetaObject.connectSlotsByName(Simulator)

    def retranslateUi(self, Simulator):
        _translate = QtCore.QCoreApplication.translate
        Simulator.setWindowTitle(_translate("Simulator", "Simulator"))
        self.textBrowser.setHtml(_translate("Simulator", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">A - амплитуда</p></body></html>"))
        self.textBrowser_2.setHtml(_translate("Simulator", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">φ0 - начальный градус отклонения</p></body></html>"))
        self.textBrowser_3.setHtml(_translate("Simulator", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">B - коэффициент затухания</p></body></html>"))
        self.textBrowser_4.setHtml(_translate("Simulator", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ω - периоди колебаний</p></body></html>"))
